In [3]:
from os.path import join
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
df = pd.read_csv(join('data','bikeshare2.csv'))
df.head(5)

datatime  season  hoilday  workingday  weather  temp   atemp  \
0  2011-01-01 0:00       1        2           0        1  9.40  14.395   
1  2011-01-01 1:00       1        2           0        1  9.02  13.635   
2  2011-01-01 2:00       1        2           0        1  9.02  13.635   
3  2011-01-01 3:00       1        2           0        1  9.84  14.395   
4  2011-01-01 4:00       1        2           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81          0       3          13      5  
1        80          0       8          32     10  
2        80          0       5          27      2  
3        75          0       3          10      4  
4        75          0       0           1     56

In [6]:
df.describe() #pandas의 describe 함수를 통해 기술통계량 확인

season  hoilday  workingday  weather      temp      atemp   humidity  \
count     8.0      8.0         8.0      8.0  8.000000   8.000000   8.000000   
mean      1.0      2.0         0.0      1.0  9.610000  13.920000  71.375000   
std       0.0      0.0         0.0      0.0  0.402563   0.393337   9.679692   
min       1.0      2.0         0.0      1.0  9.020000  13.635000  60.000000   
25%       1.0      2.0         0.0      1.0  9.305000  13.635000  60.000000   
50%       1.0      2.0         0.0      1.0  9.840000  13.635000  75.000000   
75%       1.0      2.0         0.0      1.0  9.920000  14.395000  80.000000   
max       1.0      2.0         0.0      1.0  9.920000  14.395000  81.000000   

       windspeed    casual  registered      count  
count        8.0  8.000000     8.00000   8.000000  
mean         0.0  3.625000    15.50000  15.375000  
std          0.0  2.386719    10.86278  18.531344  
min          0.0  0.000000     1.00000   1.000000  
25%          0.0  2.750000     8.50000   3.500000  
50%          0.0  3.000000    14.00000   7.500000  
75%          0.0  5.000000    23.25000  22.250000  
max          0.0  8.000000    32.00000  56.000000

In [33]:
np_data = np.array(df)
tmp=np_data[:,1:]
print(tmp)

[[1 2 0 1 9.4 14.395 81 0 3 13 5]
 [1 2 0 1 9.02 13.635 80 0 8 32 10]
 [1 2 0 1 9.02 13.635 80 0 5 27 2]
 [1 2 0 1 9.84 14.395 75 0 3 10 4]
 [1 2 0 1 9.84 14.395 75 0 0 1 56]
 [2 2 0 1 9.92 13.635 60 0 2 4 23]
 [2 2 0 1 9.92 13.635 60 0 5 22 22]
 [2 2 0 1 9.92 13.635 80 0 3 15 1]
 [2 2 0 1 9.92 13.635 80 0 1 8 5]
 [3 2 0 1 9.92 13.635 80 0 1 1 10]
 [3 2 0 1 9.92 13.635 60 0 5 2 6]
 [3 2 0 1 9.92 13.635 60 0 8 23 8]
 [3 2 0 1 9.92 13.635 81 0 4 12 48]
 [3 2 0 1 9.92 13.635 60 0 6 3 22]
 [4 2 0 1 9.92 13.635 74 0 8 20 53]
 [4 2 0 1 9.92 13.635 74 0 6 21 3]
 [4 2 0 1 9.92 13.635 73 0 2 13 11]
 [4 2 0 1 9.92 13.635 71 0 5 5 40]]


# Normalization

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler=MinMaxScaler()
scaler.fit(np_data[:,5].reshape(-1,1))
a=scaler.transform(np_data[:,5].reshape(-1,1))

#scaler가 기본적으로 column vector를 받아서 입력이 row vector인 경우 transpose를 해준다.
np.set_printoptions(precision=3) #소수점 셋째자리까지
print(np_data[:,5])
print(np_data[:,5].reshape(-1,1))
print(a)
print(np.min(np_data[:,5]), np.max(np_data[:,5]))
print(np.min(a), np.max(a))

[9.4 9.02 9.02 9.84 9.84 9.92 9.92 9.92]
[[9.4]
 [9.02]
 [9.02]
 [9.84]
 [9.84]
 [9.92]
 [9.92]
 [9.92]]
[[0.422]
 [0.   ]
 [0.   ]
 [0.911]
 [0.911]
 [1.   ]
 [1.   ]
 [1.   ]]
9.02 9.92
0.0 1.0


In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler = StandardScaler()
a = scaler.fit_transform(np_data[:,5].reshape(-1,1))

np.set_printoptions(precision=3)
print(np.mean(np_data[:,5]), np.std(np_data[:,5]))
print(np.mean(a), np.std(a))

9.610000000000001 0.3765634076752547
1.1657341758564144e-15 1.0


# Binary Transform

In [22]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold = 10)
binarizedX = binarizer.transform(np_data[:,5].reshape(-1,1))
print(np.array(np_data[:,5]))
print("============")
print(binarizedX)

[9.4 9.02 9.02 9.84 9.84 9.92 9.92 9.92]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


# OneHotEncoding

In [31]:
# One Hot Encoding은 pandas의 get_dummies함수 혹은 sklearn의 OneHotEncoder를 사용한다.

##Pandas dummy
a = pd.get_dummies(df['season'])
print(df['season'][0:10])
a.head(5)

0    1
1    1
2    1
3    1
4    1
5    2
6    2
7    2
8    2
9    3
Name: season, dtype: int64


1  2  3  4
0  1  0  0  0
1  1  0  0  0
2  1  0  0  0
3  1  0  0  0
4  1  0  0  0

In [36]:
## sklearn OneHotEncoding
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoder.fit(np_data[:,1].reshape(-1,1))
a = encoder.transform(np_data[:,1].reshape(-1,1)).toarray()
print(a)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


# Missing Value Imputation

In [45]:
from sklearn.impute import SimpleImputer

X = [[1,2],[np.nan,3],[7,6]]
imp= SimpleImputer(missing_values = np.nan, strategy = 'mean')
print(X)
imp.fit_transform(X)

[[1, 2], [nan, 3], [7, 6]]


array([[1., 2.],
       [4., 3.],
       [7., 6.]])

 # Data Merge

In [54]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [56]:
#axis 방향으로 합치라는 의미
## axis=0은 row, axis=1은 column
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [58]:
print(np.concatenate((a,b.T),axis=1))

[[1 2 5]
 [3 4 6]]


In [60]:
print(np.concatenate((a,b),axis=None))

[1 2 3 4 5 6]
