In [86]:
from os.path import join
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data Import with Pandas

In [87]:
df=pd.read_csv(join('data','bikeshare.csv'))
df.head(5) #table로 보여주어 직관적이다.

datatime  season  hoilday  count
0  2011-01-01 0:00       1        2      5
1  2011-01-01 1:00       1        2     10
2  2011-01-01 2:00       1        2      2
3  2011-01-01 3:00       1        2      4
4  2011-01-01 4:00       1        2     56

In [88]:
df.shape #data의 모양 확인

(8, 4)

In [89]:
print(df.shape[0]) #row
print(df.shape[1]) #column

8
4


In [90]:
print(df['count']) #column명을 이용한 data slicing 가능

0     5
1    10
2     2
3     4
4    56
5    23
6    22
7     1
Name: count, dtype: int64


In [91]:
print(df['count'][0:5])  #index 0~4까지 가져옴
temp=df['count']
print(temp[0:5])

0     5
1    10
2     2
3     4
4    56
Name: count, dtype: int64
0     5
1    10
2     2
3     4
4    56
Name: count, dtype: int64


In [92]:
print(df.iloc[0:4, 0:2]) #index를 이용한 data slicing // df.iloc[r,c]

          datatime  season
0  2011-01-01 0:00       1
1  2011-01-01 1:00       1
2  2011-01-01 2:00       1
3  2011-01-01 3:00       1


In [93]:
temp=df.iloc[:,3] # [:,3]에서 :은 전체, 3번 column
print(temp[0:4])

0     5
1    10
2     2
3     4
Name: count, dtype: int64


In [94]:
print(type(temp)) #data type확인 가능

<class 'pandas.core.series.Series'>


In [95]:
print(df.dtypes) #전체 data frame을 확인하려면 dtypes

datatime    object
season       int64
hoilday      int64
count        int64
dtype: object


In [96]:
print(temp.dtype) #하나의 type을 확인하려면 dtype

int64


In [97]:
new_data = pd.DataFrame({'datatime':['2011-01-01 0:00', '2011-01-01 1:00', '2011-01-01 2:00'], 'biketype':[1, 2, 3]})
new_data.head()

datatime  biketype
0  2011-01-01 0:00         1
1  2011-01-01 1:00         2
2  2011-01-01 2:00         3

In [98]:
join_data=pd.merge(df, new_data, how='inner')
join_data.head()

datatime  season  hoilday  count  biketype
0  2011-01-01 0:00       1        2      5         1
1  2011-01-01 1:00       1        2     10         2
2  2011-01-01 2:00       1        2      2         3

In [99]:
np_data=np.array(df)
print(np_data)

[['2011-01-01 0:00' 1 2 5]
 ['2011-01-01 1:00' 1 2 10]
 ['2011-01-01 2:00' 1 2 2]
 ['2011-01-01 3:00' 1 2 4]
 ['2011-01-01 4:00' 1 2 56]
 ['2011-01-01 5:00' 1 2 23]
 ['2011-01-01 6:00' 1 2 22]
 ['2011-01-01 7:00' 1 2 1]]


In [100]:
np_data.shape

(8, 4)

In [101]:
print(np_data[:,1]) #numpy는 index를 이용한 slicing만 가능하다. cloumn명으로 접근안됨
print(np_data[0,3])
print(np_data[0:2,0:2])

[1 1 1 1 1 1 1 1]
5
[['2011-01-01 0:00' 1]
 ['2011-01-01 1:00' 1]]


In [102]:
temp = np_data[:,3]
print(temp[0:3])

[5 10 2]


# Vector Calculation with numpy

numpy의 장점은 calculation이 쉽다.

In [103]:
tmp1 = np_data[0:6,3] #원소가 6개 있는 6차원 벡터로 만들었다.
tmp2 = np_data[2:8,3]
print(tmp1)
print(tmp2)

[5 10 2 4 56 23]
[2 4 56 23 22 1]


In [104]:
# vector연산은 기본적으로 cell by cell연산이다.
tmp3=tmp1+tmp2
tmp4=tmp1-tmp2
tmp5=tmp1/tmp2
tmp6=tmp1*tmp2
tmp7=np.dot(tmp1,tmp2)
print(tmp1)
print(tmp4)
print(tmp5)
print(tmp6)
print(tmp7)

[5 10 2 4 56 23]
[3 6 -54 -19 34 22]
[2.5 2.5 0.03571428571428571 0.17391304347826086 2.5454545454545454 23.0]
[10 40 112 92 1232 23]
1509


In [105]:
# matrix연산도 비슷하다.
tmp1=np_data[0:5,2:4]
tmp2=np_data[3:8,2:4]
print(tmp1)
print(tmp2)

[[2 5]
 [2 10]
 [2 2]
 [2 4]
 [2 56]]
[[2 4]
 [2 56]
 [2 23]
 [2 22]
 [2 1]]


In [106]:
tmp3=tmp1+tmp2
tmp4=tmp1-tmp2
tmp5=tmp1/tmp2
tmp6=tmp1*tmp2
tmp7=np.dot(np.transpose(tmp1),tmp2)
print(tmp1)
print(tmp4)
print(tmp5)
print(tmp6)
print(tmp7)

[[2 5]
 [2 10]
 [2 2]
 [2 4]
 [2 56]]
[[0 1]
 [0 -46]
 [0 -21]
 [0 -18]
 [0 55]]
[[1.0 1.25]
 [1.0 0.17857142857142858]
 [1.0 0.08695652173913043]
 [1.0 0.18181818181818182]
 [1.0 56.0]]
[[4 20]
 [4 560]
 [4 46]
 [4 88]
 [4 56]]
[[20 212]
 [154 770]]


# Frequently Used Functions in Numpy
- numpy의 유용한 수학함수들이다.
- 실제로 데이터를 만지다보면 자주 사용되는 함수들이다.

In [110]:
## Zeros
a=np.zeros((2,2))
print(a)
## Ones
b=np.ones((2,2))
print(b)
c= -1*np.ones((2,2))
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[-1. -1.]
 [-1. -1.]]


In [113]:
tmp1= np.array([1.1,2.2,3.3,4.4,5.5])
print(tmp1)
print(np.abs(tmp1))
print(np.sqrt(tmp1))
print(np.log(tmp1))
print(np.rint(tmp1)) #반올림
print(np.floor(tmp1)) #내림
print(np.ceil(tmp1)) #올림
print(np.min(tmp1))
print(np.max(tmp1))
print(np.mean(tmp1))
print(np.std(tmp1)) #표준편차
print(np.median(tmp1))


[1.1 2.2 3.3 4.4 5.5]
[1.1 2.2 3.3 4.4 5.5]
[1.04880885 1.4832397  1.81659021 2.0976177  2.34520788]
[0.09531018 0.78845736 1.19392247 1.48160454 1.70474809]
[1. 2. 3. 4. 6.]
[1. 2. 3. 4. 5.]
[2. 3. 4. 5. 6.]
1.1
5.5
3.3
1.5556349186104046
3.3


In [116]:
# row vector를 column vector로 변환
tmp1_prime = tmp1.reshape(-1,1)
print(tmp1)
print(tmp1_prime)

[1.1 2.2 3.3 4.4 5.5]
[[1.1]
 [2.2]
 [3.3]
 [4.4]
 [5.5]]


# Random Functions

In [119]:
a= np.random.permutation(tmp1) #데이터 섞어주는 함수
print(a)

[1.1 5.5 3.3 4.4 2.2]


In [120]:
#데이터를 원하는 분포에 맞춰서 random하게 생성해줄수도 있다.
a=np.random.normal(loc=1, scale=1, size=(10,2)) #loc-> 정규분포의 평균, scale-> 표준편차
print(a)

[[-0.11113203 -0.16055092]
 [ 1.12125656  2.12983484]
 [ 0.19747171 -1.2818058 ]
 [ 1.23850068 -0.43732839]
 [ 0.11707928  1.31089054]
 [ 1.65560751  1.44384011]
 [ 1.82449787  1.38262091]
 [ 1.70636856  1.73190912]
 [ 2.76202455  1.57861046]
 [ 2.26759513  1.19171485]]
